// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.0
// source: database/getAccount.proto

package getAccount

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GetAccountAPI_GetAccount_FullMethodName = "/GetAccountAPI/GetAccount"
)

// GetAccountAPIClient is the client API for GetAccountAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GetAccountAPIClient interface {
	GetAccount(ctx context.Context, in *GetAccountReq, opts ...grpc.CallOption) (*GetAccountRes, error)
}

type getAccountAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewGetAccountAPIClient(cc grpc.ClientConnInterface) GetAccountAPIClient {
	return &getAccountAPIClient{cc}
}

func (c *getAccountAPIClient) GetAccount(ctx context.Context, in *GetAccountReq, opts ...grpc.CallOption) (*GetAccountRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAccountRes)
	err := c.cc.Invoke(ctx, GetAccountAPI_GetAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetAccountAPIServer is the server API for GetAccountAPI service.
// All implementations must embed UnimplementedGetAccountAPIServer
// for forward compatibility.
type GetAccountAPIServer interface {
	GetAccount(context.Context, *GetAccountReq) (*GetAccountRes, error)
	mustEmbedUnimplementedGetAccountAPIServer()
}

// UnimplementedGetAccountAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGetAccountAPIServer struct{}

func (UnimplementedGetAccountAPIServer) GetAccount(context.Context, *GetAccountReq) (*GetAccountRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccount not implemented")
}
func (UnimplementedGetAccountAPIServer) mustEmbedUnimplementedGetAccountAPIServer() {}
func (UnimplementedGetAccountAPIServer) testEmbeddedByValue()                       {}

// UnsafeGetAccountAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GetAccountAPIServer will
// result in compilation errors.
type UnsafeGetAccountAPIServer interface {
	mustEmbedUnimplementedGetAccountAPIServer()
}

func RegisterGetAccountAPIServer(s grpc.ServiceRegistrar, srv GetAccountAPIServer) {
	// If the following call pancis, it indicates UnimplementedGetAccountAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GetAccountAPI_ServiceDesc, srv)
}

func _GetAccountAPI_GetAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetAccountAPIServer).GetAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GetAccountAPI_GetAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetAccountAPIServer).GetAccount(ctx, req.(*GetAccountReq))
	}
	return interceptor(ctx, in, info, handler)
}

// GetAccountAPI_ServiceDesc is the grpc.ServiceDesc for GetAccountAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GetAccountAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "GetAccountAPI",
	HandlerType: (*GetAccountAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAccount",
			Handler:    _GetAccountAPI_GetAccount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "database/getAccount.proto",
}
