// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.29.0
// source: database/selectAccount.proto

package getAccount

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SelectAccountReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountName string `protobuf:"bytes,1,opt,name=account_name,json=accountName,proto3" json:"account_name,omitempty"`
}

func (x *SelectAccountReq) Reset() {
	*x = SelectAccountReq{}
	mi := &file_database_selectAccount_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectAccountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectAccountReq) ProtoMessage() {}

func (x *SelectAccountReq) ProtoReflect() protoreflect.Message {
	mi := &file_database_selectAccount_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectAccountReq.ProtoReflect.Descriptor instead.
func (*SelectAccountReq) Descriptor() ([]byte, []int) {
	return file_database_selectAccount_proto_rawDescGZIP(), []int{0}
}

func (x *SelectAccountReq) GetAccountName() string {
	if x != nil {
		return x.AccountName
	}
	return ""
}

type SelectAccountRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId   string `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	AccountName string `protobuf:"bytes,2,opt,name=account_name,json=accountName,proto3" json:"account_name,omitempty"`
	Password    string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *SelectAccountRes) Reset() {
	*x = SelectAccountRes{}
	mi := &file_database_selectAccount_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectAccountRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectAccountRes) ProtoMessage() {}

func (x *SelectAccountRes) ProtoReflect() protoreflect.Message {
	mi := &file_database_selectAccount_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectAccountRes.ProtoReflect.Descriptor instead.
func (*SelectAccountRes) Descriptor() ([]byte, []int) {
	return file_database_selectAccount_proto_rawDescGZIP(), []int{1}
}

func (x *SelectAccountRes) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *SelectAccountRes) GetAccountName() string {
	if x != nil {
		return x.AccountName
	}
	return ""
}

func (x *SelectAccountRes) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

var File_database_selectAccount_proto protoreflect.FileDescriptor

var file_database_selectAccount_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x2f, 0x73, 0x65, 0x6c, 0x65, 0x63,
	0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x35,
	0x0a, 0x10, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52,
	0x65, 0x71, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x70, 0x0a, 0x10, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x41,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x32, 0x4b, 0x0a, 0x10, 0x53, 0x65, 0x6c, 0x65, 0x63,
	0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x41, 0x50, 0x49, 0x12, 0x37, 0x0a, 0x0d, 0x53,
	0x65, 0x6c, 0x65, 0x63, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x11, 0x2e, 0x53,
	0x65, 0x6c, 0x65, 0x63, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x1a,
	0x11, 0x2e, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52,
	0x65, 0x73, 0x22, 0x00, 0x42, 0x51, 0x5a, 0x4f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2d,
	0x76, 0x65, 0x67, 0x67, 0x69, 0x65, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x67, 0x65, 0x6e, 0x2f, 0x67, 0x6f, 0x6c,
	0x61, 0x6e, 0x67, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x2f, 0x67, 0x65, 0x74,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_database_selectAccount_proto_rawDescOnce sync.Once
	file_database_selectAccount_proto_rawDescData = file_database_selectAccount_proto_rawDesc
)

func file_database_selectAccount_proto_rawDescGZIP() []byte {
	file_database_selectAccount_proto_rawDescOnce.Do(func() {
		file_database_selectAccount_proto_rawDescData = protoimpl.X.CompressGZIP(file_database_selectAccount_proto_rawDescData)
	})
	return file_database_selectAccount_proto_rawDescData
}

var file_database_selectAccount_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_database_selectAccount_proto_goTypes = []any{
	(*SelectAccountReq)(nil), // 0: SelectAccountReq
	(*SelectAccountRes)(nil), // 1: SelectAccountRes
}
var file_database_selectAccount_proto_depIdxs = []int32{
	0, // 0: SelectAccountAPI.SelectAccount:input_type -> SelectAccountReq
	1, // 1: SelectAccountAPI.SelectAccount:output_type -> SelectAccountRes
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_database_selectAccount_proto_init() }
func file_database_selectAccount_proto_init() {
	if File_database_selectAccount_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_database_selectAccount_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_database_selectAccount_proto_goTypes,
		DependencyIndexes: file_database_selectAccount_proto_depIdxs,
		MessageInfos:      file_database_selectAccount_proto_msgTypes,
	}.Build()
	File_database_selectAccount_proto = out.File
	file_database_selectAccount_proto_rawDesc = nil
	file_database_selectAccount_proto_goTypes = nil
	file_database_selectAccount_proto_depIdxs = nil
}
