// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.0
// source: database/selectAccount.proto

package getAccount

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SelectAccountAPI_SelectAccount_FullMethodName = "/SelectAccountAPI/SelectAccount"
)

// SelectAccountAPIClient is the client API for SelectAccountAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SelectAccountAPIClient interface {
	SelectAccount(ctx context.Context, in *SelectAccountReq, opts ...grpc.CallOption) (*SelectAccountRes, error)
}

type selectAccountAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewSelectAccountAPIClient(cc grpc.ClientConnInterface) SelectAccountAPIClient {
	return &selectAccountAPIClient{cc}
}

func (c *selectAccountAPIClient) SelectAccount(ctx context.Context, in *SelectAccountReq, opts ...grpc.CallOption) (*SelectAccountRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SelectAccountRes)
	err := c.cc.Invoke(ctx, SelectAccountAPI_SelectAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SelectAccountAPIServer is the server API for SelectAccountAPI service.
// All implementations must embed UnimplementedSelectAccountAPIServer
// for forward compatibility.
type SelectAccountAPIServer interface {
	SelectAccount(context.Context, *SelectAccountReq) (*SelectAccountRes, error)
	mustEmbedUnimplementedSelectAccountAPIServer()
}

// UnimplementedSelectAccountAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSelectAccountAPIServer struct{}

func (UnimplementedSelectAccountAPIServer) SelectAccount(context.Context, *SelectAccountReq) (*SelectAccountRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SelectAccount not implemented")
}
func (UnimplementedSelectAccountAPIServer) mustEmbedUnimplementedSelectAccountAPIServer() {}
func (UnimplementedSelectAccountAPIServer) testEmbeddedByValue()                          {}

// UnsafeSelectAccountAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SelectAccountAPIServer will
// result in compilation errors.
type UnsafeSelectAccountAPIServer interface {
	mustEmbedUnimplementedSelectAccountAPIServer()
}

func RegisterSelectAccountAPIServer(s grpc.ServiceRegistrar, srv SelectAccountAPIServer) {
	// If the following call pancis, it indicates UnimplementedSelectAccountAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SelectAccountAPI_ServiceDesc, srv)
}

func _SelectAccountAPI_SelectAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SelectAccountReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SelectAccountAPIServer).SelectAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SelectAccountAPI_SelectAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SelectAccountAPIServer).SelectAccount(ctx, req.(*SelectAccountReq))
	}
	return interceptor(ctx, in, info, handler)
}

// SelectAccountAPI_ServiceDesc is the grpc.ServiceDesc for SelectAccountAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SelectAccountAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "SelectAccountAPI",
	HandlerType: (*SelectAccountAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SelectAccount",
			Handler:    _SelectAccountAPI_SelectAccount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "database/selectAccount.proto",
}
